GET http://localhost:8081/exames
content-type: application/json

###

GET http://localhost:8081/exames/listaExames
content-type: application/json

###

GET http://localhost:8080/exames/autorizacaoExame?autorizacao=false
content-type: application/json
