POST http://localhost:8080/exames
content-type: application/json

{
  "nomeExame": "ECOCARDIOGRAMA",
  "autorizacao": true
}

###
POST http://localhost:8080/exames
content-type: application/json

{
  "nomeExame": "TESTE2",
  "autorizacao": false
}

###
