PUT http://localhost:8080/exames/editarExame/2
content-type: application/json

{
  "nomeExame": "biopsia"
}

###

PUT http://localhost:8080/exames/editarExame/1
content-type: application/json

{
  "nomeExame": "ecocardiograma"
}

###