PUT http://localhost:8081/exames/editarExame/2
content-type: application/json

{
  "nomeExame": "biopsia",
  "autorizacao": true
}

###

PUT http://localhost:8080/exames/editarExame/1
content-type: application/json

{
  "nomeExame": "ecocardiograma",
  "autorizacao": false
}

###