POST http://localhost:8080/procedimentos
content-type: application/json

{
  "nomeProcedimento": "Teste",
  "especialidadesId": [1,2]
}

###
POST http://localhost:8080/procedimentos
content-type: application/json

{
  "nomeProcedimento": "TESTE2",
  "especialidadesId": [1]
}

###
