PUT http://localhost:8080/procedimentos/editarProcedimento/2
content-type: application/json

{
  "nomeProcedimento": "Consulta",
  "especialidades": [1,2]
}

###

PUT http://localhost:8080/procedimentos/editarProcedimento/1
content-type: application/json

{
  "nomeProcedimento": "Teste",
  "especialidades": [2]
}

###