POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "15/10/2020",
  "vagasOfertadas": "10",
  "especialidade":3,
  "exame": null,
  "consulta": true
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "08/10/2020",
  "vagasOfertadas": "10",
  "especialidade":3,
  "exame": null,
  "consulta": true
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "14/10/2020",
  "vagasOfertadas": "10",
  "especialidade":3,
  "exame": null,
  "consulta": true
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "18/10/2020",
  "vagasOfertadas": "10",
  "especialidade":3,
  "exame":null,
  "consulta": true
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "10/10/2020",
  "vagasOfertadas": "10",
  "especialidade":null,
  "exame": 1,
  "consulta": false
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "11/10/2020",
  "vagasOfertadas": "10",
  "especialidade":null,
  "exame": 1,
  "consulta": false
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "08/10/2020",
  "vagasOfertadas": "10",
  "especialidade":null,
  "exame": 1,
  "consulta": false
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "17/10/2020",
  "vagasOfertadas": "10",
  "especialidade":null,
  "exame": 1,
  "consulta": false
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "18/10/2020",
  "vagasOfertadas": "10",
  "especialidade":null,
  "exame": 1,
  "consulta": false
}