POST http://localhost:8080/especialidades
content-type: application/json

{
"nomeEspecialidade": "especialista"
}

###

POST http://localhost:8080/especialidades
content-type: application/json

{
  "nomeEspecialidade": "pediatria"
}

###