PUT http://localhost:8080/especialidades/atualizarEspecialidade?nomeEspecialidade=NEUROLOGIA
content-type: application/json

{
  "nomeEspecialidade": "Endocrinologia"
}

###

PUT http://localhost:8080/especialidades/atualizarEspecialidade?nomeEspecialidade=Endocrinologia
content-type: application/json

{
  "nomeEspecialidade": "Cardiologia"
}