POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "Martin Rocha Petersen",
  "cpf": "794.897.370-2",
  "carteiraSUS": "999999-9",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "Maria das Virgens Souza",
  "cpf": "107.375.204-19",
  "carteiraSUS": "999999-8",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "José Augusto do Nascimento",
  "cpf": "107.375.204-18",
  "carteiraSUS": "999999-7",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"

}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "Kandell Oliveira",
  "cpf": "107.375.204-17",
  "carteiraSUS": "999999-6",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "Martin Rocha Petersen",
  "cpf": "107.375.204-16",
  "carteiraSUS": "999999-5",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###

POST http://localhost:8080/exames
content-type: application/json

{
  "nomeExame": "ECOCARDIOGRAMA",
  "autorizacao": true
}

###
POST http://localhost:8080/exames
content-type: application/json

{
  "nomeExame": "TESTE2",
  "autorizacao": false
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "26/10/2020",
  "vagasOfertadas": "10",
  "especialidade":null,
  "exame": 2,
  "consulta": false
}

###

POST http://localhost:8080/vagas
content-type: application/json

{
  "data": "26/10/2020",
  "vagasOfertadas": "10",
  "especialidade":3,
  "exame": null,
  "consulta": true
}

###

POST http://localhost:8080/filaEspera/filaConsulta
content-type: application/json

{
  "paciente_id": 1,
  "user_id": 1,
  "especialidade_id": 3
}

###

POST http://localhost:8080/filaEspera/filaConsulta
content-type: application/json

{
  "paciente_id": 2,
  "user_id": 1,
  "especialidade_id": 3
}

###

POST http://localhost:8080/filaEspera/filaConsulta
content-type: application/json

{
  "paciente_id": 3,
  "user_id": 1,
  "especialidade_id": 3
}

###

POST http://localhost:8080/filaEspera/filaConsulta
content-type: application/json

{
  "paciente_id": 4,
  "user_id": 1,
  "especialidade_id": 3
}

###

POST http://localhost:8080/filaEspera/filaConsulta
content-type: application/json

{
  "paciente_id": 5,
  "user_id": 1,
  "especialidade_id": 3
}

###

POST http://localhost:8080/filaEspera/filaConsulta
content-type: application/json

{
  "paciente_id": 6,
  "user_id": 1,
  "especialidade_id": 3
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 2,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 3,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 4,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 5,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 6,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 2,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 3,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 4,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 5,
  "user_id": 1,
  "exame_id": 2
}

###

POST http://localhost:8080/filaEspera/filaExame
content-type: application/json

{
  "paciente_id": 6,
  "user_id": 1,
  "exame_id": 2
}

###