DELETE http://localhost:8080/pacientes/deletarCadastro?carteiraSUS=999999-8
content-type: application/json

###

DELETE http://localhost:8080/pacientes/deletarCadastro?cpf=794.897.370-2
content-type: application/json

###