POST http://localhost:8081/pacientes
content-type: application/json

{
  "nome": "Martin Rocha Petersen",
  "cpf": "794.897.370-2",
  "carteiraSUS": "999999-9",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "Maria das Virgens Souza",
  "cpf": "107.375.204-19",
  "carteiraSUS": "999999-8",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "José Augusto do Nascimento",
  "cpf": "107.375.204-18",
  "carteiraSUS": "999999-7",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"

}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "Kandell Oliveira",
  "cpf": "107.375.204-17",
  "carteiraSUS": "999999-6",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###

POST http://localhost:8080/pacientes
content-type: application/json

{
  "nome": "Martin Rocha Petersen",
  "cpf": "107.375.204-16",
  "carteiraSUS": "999999-5",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "160"
}

###
