PUT http://localhost:8080/pacientes/atualizarCadastro
content-type: application/json

{
  "nome": "Martin Petersen",
  "cpf": "794.897.370-2",
  "carteiraSUS": "sus",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "170"
}

###

PUT http://localhost:8080/pacientes/atualizarCadastro
content-type: application/json

{
  "nome": "Maria das Virgens Souza",
  "cpf": "cpf",
  "carteiraSUS": "999999-6",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "170"
}

###

PUT http://localhost:8080/pacientes/atualizarCadastro
content-type: application/json

{
  "nome": "Maria das Virgens Souza",
  "cpf": "794.897.370-00",
  "carteiraSUS": "999999-8",
  "cidade": "Natal",
  "bairro": "Pajuçara",
  "complemento": "Casa de primeiro andar",
  "dataNascimento": "21/06/1996",
  "telefone": "(84)99678-4853",
  "numero": "170"
}